import type { CoreTickWindow } from "../types";

/**
 * The minimal Timeline surface a Ruler needs. A structural interface (not
 * the concrete Timeline class) so rulers never import Timeline.ts and no
 * circular dependency exists between the two.
 */
export interface TimelineLike {
  beatToTime(beat: number): number;
  timeToBeat(time: number): number;
  /**
   * Pause-aware played seconds (a stopwatch, not tempo-scaled). Time rulers
   * read this directly rather than deriving from `beat`: transport pauses
   * break the beat<->wallclock correspondence in a way the tempo curve
   * alone can't recover (tempo events are anchored to absolute audio-clock
   * time, not elapsed play time). A deliberate, documented exception to
   * "every reading is a pure function of the beat position".
   */
  readonly position: number;
}

/**
 * A ruler interprets the beat axis into another coordinate system. Rulers
 * hold no position state: every reading is a pure function of the beat
 * position (and, for window reads, the window bounds) passed in.
 */
export interface Ruler<TWindow, TPoint> {
  /** A window-scoped reading; grid()/spans close over the window's beat range. */
  read(window: CoreTickWindow, timeline: TimelineLike): TWindow;
  /** A reading at an arbitrary beat position — feeds the reactive `current` cell. */
  at(beat: number, timeline: TimelineLike): TPoint;
}

export interface GridPoint {
  beat: number;
  time: number;
  /** Step number counted from the grid's origin, increasing forever. */
  index: number;
}

/**
 * A grid point on a *cycling* ruler. Where a linear ruler counts forever,
 * a cycle ruler folds into its region: `step` is the position within the
 * cycle, so it indexes a pattern array directly with no modulo at the call
 * site. The global count is still recoverable as `cycle * division + step`.
 */
export interface CycleGridPoint {
  beat: number;
  time: number;
  /** Position within the cycle, in [0, division). */
  step: number;
  /** Which repetition of the region this point falls in. */
  cycle: number;
}

/**
 * Guard a ruler option that a reading later divides by or advances a cursor
 * with. Zero, negative, and non-finite values don't merely produce wrong
 * numbers — a negative cycle length walks `CycleBarRuler._spans()` away from
 * its window forever, and a NaN step makes `gridPoints`' termination check
 * unreachable. Both hang inside a tick callback, so reject at construction,
 * the way TempoCurve already rejects bpm <= 0.
 */
export function assertPositiveLength(value: number, name: string): void {
  if (!Number.isFinite(value) || value <= 0) {
    throw new RangeError(`${name} must be a finite number > 0, got ${value}`);
  }
}

/**
 * Guard a ruler option used as an offset. Unlike a length, zero and negatives
 * are legitimate here — only non-finite values are rejected, because they
 * poison a reading into NaN and make `gridPoints` bail on its origin check,
 * which surfaces as a grid that silently yields nothing: no sound, no error.
 */
export function assertFiniteOffset(value: number, name: string): void {
  if (!Number.isFinite(value)) {
    throw new RangeError(`${name} must be a finite number, got ${value}`);
  }
}

/** Axis-unit beats per bar: quarter note is the axis unit (Link/MIDI convention). */
export function beatsPerBar(numerator: number, denominator: number): number {
  assertPositiveLength(numerator, "numerator");
  assertPositiveLength(denominator, "denominator");
  return (numerator * 4) / denominator;
}

/**
 * Grid points inside [startBeat, endBeat), generated by integer step index
 * (`originBeat + k * stepBeats`) rather than by accumulation — so there is
 * no float drift, and `index` is position-derived: a pure function of
 * position (`k`), never a counter. It is correct across any seek or loop
 * with no consumer reset logic (spec ST-2).
 *
 * Half-open per segment: a grid point exactly at `endBeat` is excluded, one
 * exactly at `startBeat` is included.
 */
export function* gridPoints(startBeat: number, endBeat: number, stepBeats: number, originBeat: number, timeline: TimelineLike): Generator<GridPoint> {
  // Non-finite guards are load-bearing, not defensive noise: with a NaN step
  // or origin every `beat` is NaN, so the `beat >= endBeat` return below never
  // fires and this generator spins forever in the scheduling hot path.
  if (!Number.isFinite(stepBeats) || !Number.isFinite(originBeat)) return;
  if (stepBeats <= 0 || endBeat <= startBeat) return;
  // `|| 0` normalizes -0 (e.g. ceil(-0.5)) to a plain 0 index
  const firstIndex = Math.ceil((startBeat - originBeat) / stepBeats) || 0;
  for (let index = firstIndex; ; index++) {
    const beat = originBeat + index * stepBeats;
    if (beat >= endBeat) return;
    if (beat >= startBeat) {
      yield { beat, time: timeline.beatToTime(beat), index };
    }
  }
}

/**
 * `gridPoints` with the running index folded into the cycle it belongs to.
 * `division` is the caller's steps-per-cycle, so `step` lands in
 * [0, division) and indexes a pattern of that length directly.
 *
 * Options that would make `division` unusable (0, negative, non-finite) also
 * make `stepBeats` unusable, so `gridPoints` has already returned without
 * yielding by the time the fold below could see them.
 */
export function* cycleGridPoints(
  startBeat: number,
  endBeat: number,
  stepBeats: number,
  originBeat: number,
  division: number,
  timeline: TimelineLike,
): Generator<CycleGridPoint> {
  for (const { beat, time, index } of gridPoints(startBeat, endBeat, stepBeats, originBeat, timeline)) {
    // Floored division, not `%`: JS's remainder keeps the sign of the
    // dividend, so `-1 % 16` is -1, not 15. Indices go negative for beats
    // before the origin -- legal here, since `from` may be positive and
    // seek() accepts negative beats -- and a negative step would silently
    // read past the start of a pattern array.
    const cycle = Math.floor(index / division);
    yield { beat, time, step: index - cycle * division, cycle };
  }
}
