import type { CoreTickWindow } from "../types";

/**
 * The minimal Timeline surface a Ruler needs. A structural interface (not
 * the concrete Timeline class) so rulers never import Timeline.ts and no
 * circular dependency exists between the two.
 */
export interface TimelineLike {
  beatToTime(beat: number): number;
  timeToBeat(time: number): number;
  /**
   * Pause-aware played seconds (a stopwatch, not tempo-scaled). Time rulers
   * read this directly rather than deriving from `beat`: transport pauses
   * break the beat<->wallclock correspondence in a way the tempo curve
   * alone can't recover (tempo events are anchored to absolute audio-clock
   * time, not elapsed play time). A deliberate, documented exception to
   * "every reading is a pure function of the beat position".
   */
  readonly position: number;
}

/**
 * A ruler interprets the beat axis into another coordinate system. Rulers
 * hold no position state: every reading is a pure function of the beat
 * position (and, for window reads, the window bounds) passed in.
 */
export interface Ruler<TWindow, TPoint> {
  /** A window-scoped reading; grid()/spans close over the window's beat range. */
  read(window: CoreTickWindow, timeline: TimelineLike): TWindow;
  /** A reading at an arbitrary beat position — feeds the reactive `current` cell. */
  at(beat: number, timeline: TimelineLike): TPoint;
}

export interface GridPoint {
  beat: number;
  time: number;
  index: number;
}

/** Axis-unit beats per bar: quarter note is the axis unit (Link/MIDI convention). */
export function beatsPerBar(numerator: number, denominator: number): number {
  return (numerator * 4) / denominator;
}

/**
 * Grid points inside [startBeat, endBeat), generated by integer step index
 * (`originBeat + k * stepBeats`) rather than by accumulation — so there is
 * no float drift, and `index` is position-derived: a pure function of
 * position (`k`), never a counter. It is correct across any seek or loop
 * with no consumer reset logic (spec ST-2).
 *
 * Half-open per segment: a grid point exactly at `endBeat` is excluded, one
 * exactly at `startBeat` is included.
 */
export function* gridPoints(startBeat: number, endBeat: number, stepBeats: number, originBeat: number, timeline: TimelineLike): Generator<GridPoint> {
  if (stepBeats <= 0 || endBeat <= startBeat) return;
  // `|| 0` normalizes -0 (e.g. ceil(-0.5)) to a plain 0 index
  const firstIndex = Math.ceil((startBeat - originBeat) / stepBeats) || 0;
  for (let index = firstIndex; ; index++) {
    const beat = originBeat + index * stepBeats;
    if (beat >= endBeat) return;
    if (beat >= startBeat) {
      yield { beat, time: timeline.beatToTime(beat), index };
    }
  }
}
